project-info {
  version: "current"
  shared-info {
    jdk-versions: ["OpenJDK 8", "OpenJDK 11", "OpenJDK 17"]
    issues: {
      url: "https://github.com/pjfanning/pekko-diagnostics/issues"
      text: "Github issues"
    }
    release-notes: {
      url: "https://github.com/pjfanning/pekko-diagnostics/releases"
      text: "Github releases"
    }
    forums: [
      {
        text: "GitHub Discussions"
        url: "https://github.com/pjfanning/pekko-diagnostics/discussions"
      }
    ]
  }
  akka-diagnostics: ${project-info.shared-info} {
    title: "Pekko Diagnostics"
    jpms-name: "com.github.pjfanning.pekko.diagnostics"
    levels: [
      {
        readiness: Incubating
        since: "2022-11-28"
        since-version: "2.0.0-M1"
      }
    ]
  }
}
