name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  check-code-style:
    name: Checks
    runs-on: ubuntu-22.04
    if: github.repository == 'pjfanning/pekko-diagnostics'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Cache Coursier cache
        uses: coursier/cache-action@v8

      - name: Set up JDK 8
        uses: coursier/setup-action@v2
        with:
          jvm: temurin:1.8.0

      - name: Code style check, compilation and binary-compatibility check
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt scalafmtCheckAll scalafmtSbtCheck headerCheck +Test/compile
          
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    if: github.repository == 'pjfanning/pekko-diagnostics'
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Cache Coursier cache
        uses: coursier/cache-action@v8

      - name: Set up JDK ${{ matrix.javaVersion }}
        uses: coursier/setup-action@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.javaVersion }}

      - name: sbt test
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt test

  check-docs:
    name: Check Docs
    runs-on: ubuntu-22.04
    if: github.repository == 'pjfanning/pekko-diagnostics'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        uses: coursier/cache-action@v8

      - name: Set up JDK 17
        uses: coursier/setup-action@v2
        with:
          jvm: temurin:1.17.0

      - name: Create all API docs for artifacts/website and all reference docs
        run: sbt "unidoc; docs/paradox"
